[module/bspwm]
type = internal/bspwm

; Mostra apenas os desktops do monitor onde a barra está
pin-workspaces = true

; Cria handler de clique para focar o desktop
enable-click = true

; Cria handler de scroll para ciclar os desktops
enable-scroll = true

; Inverte o scroll
reverse-scroll = true

; Desktop ativo no monitor COM foco global (Laranja)
label-focused = %name%
label-focused-foreground = ${colors.white}
label-focused-background = ${colors.background-alt}
label-focused-underline = ${colors.secondary}
label-focused-padding = 1

; Desktop ativo no monitor SEM foco global (Roxo)
label-dimmed-focused = %name%
label-dimmed-focused-foreground = ${colors.white}
label-dimmed-focused-background = ${colors.background-alt}
label-dimmed-focused-underline = ${colors.primary}
label-dimmed-focused-padding = 1

; Desktop com janelas mas não ativo
label-occupied = %name%
label-occupied-underline = ${colors.background}
label-occupied-padding = 1

; Desktop com janela urgente
label-urgent = %name%
label-urgent-foreground = ${colors.secondary}
label-urgent-background = ${colors.background-alt}
label-urgent-underline = ${colors.alert}
label-urgent-padding = 1

; Desktop sem janelas
label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1
