#! /bin/sh

# --------------------------------------
# AUTOSTARTS
# --------------------------------------

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh -b &

$HOME/dotfiles/scripts/change_wallpaper.sh &

nm-applet &

# --------------------------------------
# OTHERS
# --------------------------------------

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        2
bspc config window_gap          7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc config automatic_scheme longest_side
