#! /bin/sh

# --------------------------------------
# VARIABLES
# --------------------------------------
export GTK_THEME=Adwaita:dark
export QT_QPA_PLATFORMTHEME=qt5ct

# --------------------------------------
# FUNCTIONS
# --------------------------------------

run() {
	if ! pgrep -f -x "$1" > /dev/null; then
		"$@" &
	fi
}

rerun() {
	pkill -x "$1"
	sleep 0.2
	"$@" &
}

# --------------------------------------
# AUTOSTARTS
# --------------------------------------

run sxhkd
run nm-applet
rerun picom --config $HOME/.config/picom/picom.conf -b

$HOME/.config/polybar/launch.sh -b &
$HOME/dotfiles/scripts/change_wallpaper.sh &

# --------------------------------------
# MONITORES
# --------------------------------------
# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d 1 2 3 4 5 6 7 8 9 10

monitors=$(bspc query -M)
monitor_count=$(echo "$monitors" | wc -l)

if [ "$monitor_count" -eq 2 ]; then
    # Se houver 2 monitores:
    # Atribui 1-5 ao primeiro e 6-10 ao segundo
    monitor1=$(echo "$monitors" | sed -n '1p')
    monitor2=$(echo "$monitors" | sed -n '2p')

    bspc monitor "$monitor1" -d 1 2 3 4
    bspc monitor "$monitor2" -d 5 6 7 8 9 10

    xrandr --output DP2 --primary --auto --output VGA1 --auto --left-of DP2
else
    # Se houver apenas 1 (ou mais de 2, como fallback)
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

# --------------------------------------
# CONFIGS
# --------------------------------------

bspc config border_width        2
bspc config window_gap          7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config automatic_scheme longest_side

# --------------------------------------
# RULES
# --------------------------------------

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# --------------------------------------
# OTHERS
# --------------------------------------

xdg-user-dirs-update &