#! /bin/sh

# --------------------------------------
# VARIABLES
# --------------------------------------
export GTK_THEME=Adwaita:dark
export QT_QPA_PLATFORMTHEME=qt5ct

# --------------------------------------
# FUNCTIONS
# --------------------------------------

run() {
	if ! pgrep -f -x "$1" > /dev/null; then
		"$@" &
	fi
}

rerun() {
	pkill -x "$1"
	sleep 0.2
	"$@" &
}

# --------------------------------------
# AUTOSTARTS
# --------------------------------------

systemctl --user import-environment DISPLAY XAUTHORITY
systemctl --user start bspwm-session.target

run caffeine start
run sxhkd
run nm-applet
run numlockx on
rerun picom --config $HOME/.config/picom/picom.conf -b

$HOME/.config/polybar/launch.sh -b &
$HOME/dotfiles/scripts/change_wallpaper.sh &

# --------------------------------------
# MONITORES
# --------------------------------------
# Detecta todos os monitores conectados, posiciona via xrandr
# e atribui os desktops 1-10 a cada um genericamente.

$HOME/dotfiles/scripts/bspwm_monitor_setup.sh

# --------------------------------------
# CONFIGS
# --------------------------------------

bspc config border_width        2
bspc config window_gap          7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config automatic_scheme longest_side

# --------------------------------------
# RULES
# --------------------------------------

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# --------------------------------------
# OTHERS
# --------------------------------------

xdg-user-dirs-update &
