total_frames = 74;

# Plymouth exige while
i = 0;
while (i < total_frames) {
    images[i] = Image("frame_" + i + ".png");
    i = i + 1;
}

sprite = Sprite();
screen_width = Window.GetWidth();
screen_height = Window.GetHeight();

Window.SetBackgroundTopColor(0, 0, 0);
Window.SetBackgroundBottomColor(0, 0, 0);

progress = 0;

fun refresh_callback() {
    frame_idx = Math.Int(progress) % total_frames;
    img = images[frame_idx];
    
    sprite.SetImage(img);
    sprite.SetX(screen_width / 2 - img.GetWidth() / 2);
    sprite.SetY(screen_height / 2 - img.GetHeight() / 2);
    
    # 0.2 (~12 fps), 0.25 (~15 fps), 0.4 (~24 fps)
    progress = progress + 0.4;
}

Plymouth.SetRefreshFunction(refresh_callback);
