[opener]
browser = [
    { run = 'firefox "$@"', block = false, desc = "Firefox" }
]
pdf_reader = [
    { run = 'firefox "$@"', block = false, desc = "Firefox" }
]

[open]
rules = [
    { url = "*.html", use = "browser" },
    { mime = "text/html", use = "browser" },
    
    { url = "*.pdf", use = "pdf_reader" },
    { mime = "application/pdf", use = "pdf_reader" }
]
