[opener]
browser = [
    { run = 'xdg-open %s1', orphan = true, desc = "xdg-open" },
    { run = 'firefox %s1', orphan = true, desc = "Firefox" }
]
pdf_reader = [
    { run = 'xdg-open %s1', orphan = true, desc = "xdg-open" },
    { run = 'firefox %s1', orphan = true, desc = "Firefox" }
]

[open]
prepend_rules = [
    { url = "*.html", use = "browser" },
    { mime = "text/html", use = "browser" },
    
    { url = "*.pdf", use = "pdf_reader" },
    { mime = "application/pdf", use = "pdf_reader" }
]


